# Generated by Django 4.2.3 on 2023-07-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnglishProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('IELTS', 'IELTS'), ('PTE', 'PTE'), ('TOEFL', 'TOEFL')], max_length=10)),
                ('test_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Created', 'Created'), ('Submitted', 'Submitted'), ('Offer', 'Offer'), ('Visa Created', 'Visa Created'), ('Visa Submitted', 'Visa Submitted'), ('Docs Requested', 'Docs Requested'), ('Granted', 'Granted'), ('Rejected', 'Rejected'), ('Enrolled', 'Enrolled')], default='Interested', max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('college_location', models.CharField(max_length=255)),
                ('course_start_date', models.DateField()),
                ('english_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.englishproficiency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.student')),
            ],
        ),
    ]
