# Generated by Django 4.2.3 on 2023-08-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_purpose', models.CharField(blank=True, choices=[('Inquiring', 'Inquiring'), ('Class Enrollment', 'Class Enrollment'), ('Abroad Enrollment', 'Abroad Enrollment')], max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('Interested', 'Interested'), ('Created', 'Created'), ('Submitted', 'Submitted'), ('Offer', 'Offer'), ('Visa Created', 'Visa Created'), ('Visa Submitted', 'Visa Submitted'), ('Docs Requested', 'Docs Requested'), ('Granted', 'Granted'), ('Rejected', 'Rejected'), ('Enrolled', 'Enrolled')], default='Interested', max_length=20, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_title', models.CharField(blank=True, max_length=150, null=True)),
                ('degree_level', models.CharField(blank=True, max_length=50, null=True)),
                ('passed_year', models.DateField(blank=True, null=True)),
                ('course_start_date', models.DateField(blank=True, null=True)),
                ('course_end_date', models.DateField(blank=True, null=True)),
                ('academic_score_category', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('GPA', 'GPA')], max_length=20, null=True)),
                ('academic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('ielts_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('toefl_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pte_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gre_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gmat_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sat_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other_language', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.country')),
                ('interested_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.course')),
                ('interested_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('file', models.FileField(upload_to='applicant_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('income_source', models.CharField(choices=[('Admission Commission', 'Admission Commission'), ('Visa Processing Commission', 'Visa Processing Commission'), ('Other', 'Other')], max_length=200)),
                ('total_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unpaid_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.country')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
            ],
            options={
                'unique_together': {('applicant', 'description')},
            },
        ),
    ]
