# Generated by Django 4.2.3 on 2023-08-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='image',
            new_name='logo',
        ),
    ]
