# Generated by Django 4.2.3 on 2023-08-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='updated_at',
        ),
    ]
