# Generated by Django 4.2.3 on 2023-08-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_commission'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('income_source', models.CharField(choices=[('Admission Commission', 'Admission Commission'), ('Visa Processing Commission', 'Visa Processing Commission'), ('Other', 'Other')], default='Other', max_length=100)),
                ('total_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unpaid_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.country')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.institution')),
            ],
        ),
    ]
