# Generated by Django 4.2.3 on 2023-08-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnglishProficiency',
        ),
    ]
