# Generated by Django 4.2.3 on 2023-07-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='documents',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
