# Generated by Django 4.2.3 on 2023-08-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_classschedule_duration'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='dob',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='academic_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='academic_score_category',
            field=models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('GPA', 'GPA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_purpose',
            field=models.CharField(blank=True, choices=[('Inquiring', 'Inquiring'), ('Class Enrollment', 'Class Enrollment'), ('Abroad Enrollment', 'Abroad Enrollment')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='application.document'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interested_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.country'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.course'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passed_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed'), ('Visa Created', 'Visa Created'), ('Visa Submitted', 'Visa Submitted'), ('Docs Requested', 'Docs Requested'), ('Granted', 'Granted'), ('Enrolled', 'Enrolled')], default='Interested', max_length=20, null=True),
        ),
    ]
