# Generated by Django 4.2.3 on 2023-08-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='income_source',
            field=models.CharField(choices=[('Admission Commission', 'Admission Commission'), ('Visa Processing Commission', 'Visa Processing Commission'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
