# Generated by Django 4.2.3 on 2023-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_applicant_dob_alter_applicant_academic_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='documents',
            field=models.ManyToManyField(to='application.document'),
        ),
    ]
