# Generated by Django 4.2.3 on 2023-07-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applicant_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('file', models.FileField(upload_to='applicant_documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='documents',
        ),
        migrations.AddField(
            model_name='applicant',
            name='documents',
            field=models.ManyToManyField(to='application.document'),
        ),
    ]
