# Generated by Django 4.2.3 on 2023-08-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_applicant_created_at_remove_applicant_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='course_end_date',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='course_start_date',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='passed_year',
        ),
    ]
