# Generated by Django 4.2.3 on 2023-08-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_delete_englishproficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='interested_course',
        ),
    ]
