# Generated by Django 4.2.4 on 2023-09-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('purpose', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='application.applicant')),
            ],
        ),
    ]
