# Generated by Django 4.2.3 on 2023-08-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applicant_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed'), ('Visa Created', 'Visa Created'), ('Visa Submitted', 'Visa Submitted'), ('Docs Requested', 'Docs Requested'), ('Granted', 'Granted'), ('Enrolled', 'Enrolled')], default='Created', max_length=20, null=True),
        ),
    ]
