# Generated by Django 4.2.3 on 2023-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_applicant_course_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='academic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gmat_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gre_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ielts_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='other_language',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pte_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sat_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed'), ('Visa Created', 'Visa Created'), ('Visa Submitted', 'Visa Submitted'), ('Docs Requested', 'Docs Requested'), ('Granted', 'Granted'), ('Enrolled', 'Enrolled')], default='Interested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='toefl_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
