# Generated by Django 4.2.4 on 2023-09-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='documents', to='application.document'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_payment', to='application.applicant'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_invoice', to='application.applicant')),
            ],
        ),
    ]
