# Generated by Django 4.2.3 on 2023-08-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_commission_income_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
    ]
