# Generated by Django 4.2.3 on 2023-08-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_status_payment_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('applicant', 'description')},
        ),
    ]
