# Generated by Django 4.2.4 on 2023-09-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_quote_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant'),
        ),
    ]
