# Generated by Django 4.2.3 on 2023-08-03 07:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major_cities', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('visa_requirements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('course_website', models.URLField(blank=True)),
                ('course_image', models.ImageField(blank=True, upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Counseling', 'Counseling'), ('Visa Processing', 'Visa Processing'), ('Admission Assistance', 'Admission Assistance'), ('Scholarship Guidance', 'Scholarship Guidance'), ('Test Preparation', 'Test Preparation'), ('Document Verification', 'Document Verification'), ('Interview Preparation', 'Interview Preparation'), ('Application Review', 'Application Review'), ('Career Counseling', 'Career Counseling')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_country', models.CharField(max_length=100)),
                ('preferred_course', models.CharField(max_length=255)),
                ('date_of_enquiry', models.DateField()),
                ('enquiry_type', models.CharField(choices=[('General', 'General Inquiry'), ('Visa', 'Visa Inquiry'), ('Course', 'Course Inquiry')], max_length=20)),
                ('enquiry_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('preferred_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('enquiry_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
