# Generated by Django 4.2.3 on 2023-08-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_classschedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('test_date', models.DateField()),
                ('test_time', models.TimeField()),
                ('result_date', models.DateField()),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.classschedule')),
            ],
        ),
    ]
