# Generated by Django 4.2.3 on 2023-08-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_classschedule_tag_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to='institution_logos/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.country')),
                ('courses', models.ManyToManyField(related_name='institutions', to='service.course')),
            ],
        ),
    ]
