# Generated by Django 4.2.4 on 2023-09-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_test_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='english_profficiency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='min_english_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='min_gpa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
