# Generated by Django 4.2.3 on 2023-08-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_classschedule_price_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='logo',
        ),
    ]
