# Generated by Django 4.2.3 on 2023-08-08 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_remove_service_price_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('income_source', models.CharField(choices=[('Admission Commission', 'Admission Commission'), ('Visa Processing Commission', 'Visa Processing Commission'), ('Other', 'Other')], default='Other', max_length=100)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.country')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.institution')),
            ],
        ),
    ]
