# Generated by Django 4.2.3 on 2023-08-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
