# Generated by Django 4.2.3 on 2023-08-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='courses',
        ),
    ]
