# Generated by Django 4.2.3 on 2023-08-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_institution_institution_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='start_time',
        ),
    ]
