# Generated by Django 4.2.3 on 2023-08-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='service.tag'),
        ),
    ]
