# Generated by Django 4.2.3 on 2023-08-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='courses',
            field=models.ManyToManyField(to='service.course'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
