# Generated by Django 4.2.3 on 2023-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_institution_courses_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
