# Generated by Django 4.2.3 on 2023-08-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_tag_created_at_remove_tag_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='event_status',
        ),
    ]
