# Generated by Django 4.2.3 on 2023-08-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_rename_name_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
